#! /bin/bash
#SBATCH -N 1
#SBATCH -J featCounts
#SBATCH -o OUT/featCounts-%A_%a.out
#SBATCH -t 2:00:00
#SBATCH --array=1-6 # job array index 
#SBATCH --mail-type=ALL
#SBATCH --mail-user=<email>
#SBATCH --cpus-per-task=6

#######################################
module load gcc/8.2.0
module load subread/1.6.2

set -x

########################################

out=
BAM=

gtf=/bgfs/genomics/workshops/2020s/RNASeq_data_analysis/Refs/Homo_sapiens.GRCh38.97.gtf

#########################################


file=$BAM/${SLURM_ARRAY_TASK_ID}*_chr21.bam
sample=`basename $file`


mkdir -p $out


featureCounts -t exon \
              -g gene_id \
              -s 0 \
              -a $gtf \
              -o $out/${sample%.bam}.txt \
              -T 2 \
              $file
