#! /bin/bash
#SBATCH -N 1
#SBATCH -J HISAT2
#SBATCH -t 1:00:00
#SBATCH -c 3
#SBATCH -o OUT/hisat2-%A_%a.out
#SBATCH --array=1-6 # job array index 
#SBATCH --mail-type=ALL
#SBATCH --mail-user=<email>
#############################


## HISAT2 set-up
module load gcc/8.2.0
module load hisat2/2.1.0
module load samtools/1.9

set -x

################################

trimfastq=
out=

ref=/bgfs/genomics/workshops/2020s/RNASeq_data_analysis/Refs/GRCh38_index_chr21/GRCh38_index_chr21

####################################

mkdir -p $out

# take input fastq file
fastqfile=$trimfastq/${SLURM_ARRAY_TASK_ID}*_1.cutadapt.fastq.gz 
# obtain only the file name and exclude the full path
filename=`basename $fastqfile`
# get sample name
sample=${filename%_1.cutadapt.fastq.gz}

hisat2 -x $ref \
        -S $out/${sample}.sam \
        -p 3 \
        --dta \
        -1 $fastqfile \
        -2 ${fastqfile%_1.cutadapt.fastq.gz}_2.cutadapt.fastq.gz 
 
samtools view -@ 3 -h -o $out/${sample}.bam $out/${sample}.sam       

